version: "2"

build:
  os: "ubuntu-20.04"
  apt_packages:
    - build-essential
    - python3-dev
  tools:
    python: "3.11"

python:
  install:
    - requirements: requirements1.txt
    - requirements: requirements2.txt
    - requirements: docs/requirements.txt
    - method: pip
      path: .

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: true
