name: Build documentation

on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  documentation:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        sudo apt update
        python -m pip install --upgrade --no-cache-dir pip setuptools
        python -m pip install --exists-action=w --no-cache-dir -r requirements1.txt
        python -m pip install --exists-action=w --no-cache-dir -r requirements2.txt
        python -m pip install --exists-action=w --no-cache-dir -r docs/requirements.txt
        python -m pip install --upgrade --upgrade-strategy eager --no-cache-dir .

    - name: Build documentation
      # Build the documentation, you can use this command locally
      run: |
        cd docs/source
        python -m sphinx -T -W --keep-going -b html -d _build/doctrees -D language=en . docs/html
